---
title: "Alternative fuel"
author: "Jessica Hunter"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
```

## Intro 

This scripts plots the public location of ethanol 85 fuel in the US

## Libraries

```{r, results='hide'}
library(tidyverse)
library(maps)
library(ggimage)
library(magick)
library(here)
```

## Load data

```{r, results='hide'}
stations <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-01/stations.csv')

```

## Clean and sort Data

```{r}

clean <- stations %>% 
  filter(FUEL_TYPE_CODE=="E85" & ACCESS_CODE == "public") 

 states <-map_data("state")
   
  e85<- image_read2(here("altfuel6", "data", "e85.png"), )
  #e85

#clean
```
## Analyze Data

```{r}
 ggplot()+
    geom_polygon(data = states, mapping = aes(x = long, y = lat, group = group, alpha = 0.5, fill = region))+
    geom_point(clean, mapping = aes(x=X, y = Y))+
    guides(fill = "none", alpha = "none")
  
  
   # geom_image(clean, mapping = aes(x=X, y=Y, image = e85))
  
```

