---
title: "Eramus"
author: "Jessica Hunter"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
```
## Intro
This script takes the data for the foreign exhange programs and plots the number of students received and sent to the countries in a bi-directional bar plot.

## Libraries

```{r, results='hide'}
library(tidyverse)
library(countrycode)
```

## Read in Data
```{r, results='hide'}
erasmus <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-08/erasmus.csv')
```

## Viewing the data
```{r eval=FALSE}
head(erasmus)
slice_sample(erasmus)
unique(erasmus$academic_year)

guess_field(erasmus$sending_country_code)
```

## Cleaning the data

```{r}


erasmusclean <- erasmus %>% 
  mutate_at(c("sending_country_code", "receiving_country_code"), ~countrycode(., origin = "eurostat", destination = "country.name")) %>% 
  select(sendingcountry = sending_country_code,
         receivingcountry = receiving_country_code,
         academic_year,
         participants) %>% 
  filter(sendingcountry!=receivingcountry) 

receiving <- erasmusclean %>% 
  group_by(receivingcountry, academic_year, .add = TRUE) %>% 
  summarise(received = sum(participants)) %>% 
  select(country = receivingcountry, 
         academic_year, received)

sending<- erasmusclean %>% 
  group_by(sendingcountry, academic_year, .add = TRUE) %>% 
  summarise(sent = sum(participants)) %>% 
  select(country = sendingcountry, 
         academic_year, sent) 

exchange <- receiving %>% 
  full_join(sending) %>% 
  pivot_longer(cols = 3:4,names_to = "direction",
               values_to = "value") %>% 
  mutate(value = replace_na(value, 0)) 


```

## Analyze the Data

```{r}

ggplot(exchange, aes(x=fct_reorder(country,  value), 
            y = ifelse(direction == "sent", -value, value), 
            fill = direction))+
   geom_col() +
  coord_flip()+
  labs(y = "Number of foreign exhange students",
       x = "Countries",
       title = "Foreign Exchange Students leaving/entering countries 2014-2020Academic years")
```



