---
title: "College Sports"
author: "Jessica Hunter"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE)
```

# Intro 

This script takes the sports data and plots the schools that have women who participate in rowing and plots them by percentage
## Libraries
```{r}
library(tidyverse)
library(maps)
library(mapdata)
library(ggmap)
```

## Read in Data
```{r, results='hide'}
sports <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-29/sports.csv')

```

## Clean the data

```{r}

fems<- sports %>% 
  filter(year == 2019, # filters the year
         sum_partic_women != 0, # removes the rows with no participation
         sports == "Rowing") %>% # filters out rowing sport
  select(femsum = sum_partic_women, # select and edit the colum names
         sports, state_cd, institution_name, zip_text,
         femtotal = ef_female_count) %>% 
  mutate(percentparti = femsum/femtotal, # creates new columns of percent
         zip_text = str_sub(zip_text, 1,5), # shortens string to only 5 digits
         region = if_else(state_cd == "DC", "District of Columbia",
                          state.name[match(state_cd, state.abb)])) %>% # fixes the DC name and changes the other names from 2 letter to full names
  mutate(latlon = geocode(zip_text)) # finds the latitudes and longitudes using zip


states <- map_data("state") # gets USE states map data for drawing
        



```

## Analyze the data

```{r}
ggplot()+
  geom_polygon(data = states, 
               aes(x = long, # maps x and y
                   y = lat, 
                   group = group, #  important for map not look weird
                   fill = region), # colors states
               alpha = 0.5)+ # transparency
  geom_point(data = fems, aes(x = latlon$lon, # maps lat and long points
                              y = latlon$lat, 
                              size = percentparti, # maps participation
                              color =  percentparti))+
  coord_map()+ 
  theme_void()+ # removes the grid background
  guides(fill = "none", # removes some legends
         color = "none",
         size = guide_legend("Percent Participation"))+ # labels legend
  labs(title = "Rowing participation for Women in Higher Education Institutions in 2019") # adds title

```


